In [5]:
from IPython.display import display, HTML
display(HTML("<font color='#000000'><b><span style='font-size: 20px;'>Uber Fares</span></b></font>"))

In [6]:
from IPython.display import display, HTML
display(HTML("<font color='#000000'><b><span style='font-size: 20px;'>Machine Learning</span></b></font><br><br>"
             "<font color='#000000'><b>Francisca Teixeira</b> (20241702)</font><br>"
             "<font color='#000000'><b>Carlota Marto</b> (20241729)</font>"))

In [7]:
import pandas as pd

In [14]:
data = pd.read_csv('uber.csv', index_col=0)
data.head(100)

,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
24238194,2015-05-07 19:52:06.0000003,7.5,2015-05-07 19:52:06 UTC,-73.999817,40.738354,-73.999512,40.723217,1
27835199,2009-07-17 20:04:56.0000002,7.7,2009-07-17 20:04:56 UTC,-73.994355,40.728225,-73.994710,40.750325,1
44984355,2009-08-24 21:45:00.00000061,12.9,2009-08-24 21:45:00 UTC,-74.005043,40.740770,-73.962565,40.772647,1
25894730,2009-06-26 08:22:21.0000001,5.3,2009-06-26 08:22:21 UTC,-73.976124,40.790844,-73.965316,40.803349,3
17610152,2014-08-28 17:47:00.000000188,16.0,2014-08-28 17:47:00 UTC,-73.925023,40.744085,-73.973082,40.761247,5
...,...,...,...,...,...,...,...,...
25431833,2015-04-11 08:47:47.0000001,9.5,2015-04-11 08:47:47 UTC,-73.978432,40.752399,-74.000427,40.742119,1
44792012,2011-10-03 20:29:00.000000179,4.5,2011-10-03 20:29:00 UTC,-73.990055,40.756413,-73.983047,40.756727,3
18571020,2010-04-26 03:12:44.0000001,3.3,2010-04-26 03:12:44 UTC,-73.982326,40.731314,-73.989649,40.734398,1
37942404,2011-11-18 09:51:00.000000166,30.9,2011-11-18 09:51:00 UTC,-73.995888,40.759078,-73.865005,40.770452,1
29024472,2009-08-30 14:03:55.0000002,26.9,2009-08-30 14:03:55 UTC,-73.990137,40.756007,-73.929361,40.774553,1

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200000 entries, 24238194 to 11951496
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   key                200000 non-null  object
 1   fare_amount        200000 non-null  float64
 2   pickup_datetime    200000 non-null  object
 3   pickup_longitude   200000 non-null  float64
 4   pickup_latitude    200000 non-null  float64
 5   dropoff_longitude  199999 non-null  float64
 6   dropoff_latitude   199999 non-null  float64
 7   passenger_count    200000 non-null  int64
dtypes: float64(5), int64(1), object(2)
memory usage: 13.7+ MB

In [16]:
data.isnull().sum()

key                  0
fare_amount          0
pickup_datetime      0
pickup_longitude     0
pickup_latitude      0
dropoff_longitude    1
dropoff_latitude     1
passenger_count      0
dtype: int64

In [17]:
data[data['dropoff_longitude'].isna()]

,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
32736015,2013-07-02 03:51:57.0000001,24.1,2013-07-02 03:51:57 UTC,-73.950581,40.779692,NaN,NaN,0

In [20]:
data = data.drop(32736015)

In [21]:
data.isnull().sum()

key                  0
fare_amount          0
pickup_datetime      0
pickup_longitude     0
pickup_latitude      0
dropoff_longitude    0
dropoff_latitude     0
passenger_count      0
dtype: int64

In [39]:
duplicate_records = data[data.duplicated(keep=False)]
duplicate_records

Empty DataFrame
Columns: [key, fare_amount, pickup_datetime, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count]
Index: []

In [41]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
fare_amount,199999.0,11.359892,9.901760,-52.000000,6.000000,8.500000,12.500000,499.000000
pickup_longitude,199999.0,-72.527631,11.437815,-1340.648410,-73.992065,-73.981823,-73.967154,57.418457
pickup_latitude,199999.0,39.935881,7.720558,-74.015515,40.734796,40.752592,40.767158,1644.421482
dropoff_longitude,199999.0,-72.525292,13.117408,-3356.666300,-73.991407,-73.980093,-73.963658,1153.572603
dropoff_latitude,199999.0,39.923890,6.794829,-881.985513,40.733823,40.753042,40.768001,872.697628
passenger_count,199999.0,1.684543,1.385995,0.000000,1.000000,1.000000,2.000000,208.000000